### ISSUE TITLE
map_go_annot has an error

### ISSUE THREAD

**Issue by ghadirli** [vitkl/ParetoTI#1]
Hi,
I got the error below when I try to follow your [example](https://vitkl.github.io/ParetoTI/articles/Hepatocyte_example.html) and then when I run the 
```
go_annot = map_go_annot(taxonomy_id = 10090, keys = rownames(hepatocytes),
                        columns = c("GOALL"), keytype = "ALIAS",
                        ontology_type = c("CC"))
```

I got the error below.
how can I fix it?
```
snapshotDate(): 2019-05-02
downloading 0 resources
loading from cache 
    ‘AH70573 : 77319’
Error: failed to load resource
  name: AH70573
  title: org.Mm.eg.db.sqlite
  reason: database disk image is malformed
In addition: Warning messages:
1: Couldn't set cache size: database disk image is malformed
Use `cache_size` = NULL to turn off this warning. 
2: Couldn't set synchronous mode: database disk image is malformed
Use `synchronous` = NULL to turn off this warning. 
```

**Comment by vitkl** [comment]
As it says in the error message, your database is probably broken. Try removing `~/.AnnotationHub/` folder in your home directory (could depend on the system).
Also check that you can use the [AnnotationHub](https://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/AnnotationHub-HOWTO.html) directly to get `AH70573` mouse gene annotations.
