### ISSUE TITLE
Matlab 2018 compatible

### ISSUE THREAD

**Issue by luksen99** [vitkl/ParetoTI#2]
Great software! I tried to run the example files on Matlab 2018 version and found two updates: 

- When running the "Synthetic"- example, the parameter `Buffersize` in order to load in the data is no longer required.

- The function `princomp` got replaced by `pca` but out and input remain the same.

**Comment by vitkl** [comment]
Sorry for a delay. I don't think this issue relates to this package because the package does not use Matlab.
