### ISSUE TITLE
Calculating effect vector angle from front

### ISSUE THREAD

**Issue by dpcook** [vitkl/ParetoTI#3]
Hey! Fantastic package--really enjoying playing around with it.

I couldn't see anything for it in the source code, but I was just wondering if you would have a strategy to calculate the angle of an effect vector to the Pareto front. 

Talking through my thoughts here, I could imagine determining the front for some control data, embed new data (eg. cells following some perturbation) in the same PC space, and then perhaps based on distances to each archetype, you could calculate an angle. Do you have any thoughts on how this could be implemented or if I'm missing something?

I appreciate it!

David

**Comment by vitkl** [comment]
Hi David,

This is an interesting question. I do not understand what exactly you mean by the angle of an effect. Based on my understanding of the gene expression data, a perturbation will likely create a new cell state expressing new genes (or a new combination of genes) - which when analysed in this framework will result in a new archetype. PC embedding of perturbed cells will rely on genes expressed before the perturbation so may not properly account for new genes.
I think it is most helpful to think about perturbations and Pareto front in the context of morphological phenotypes.
https://royalsocietypublishing.org/doi/full/10.1098/rstb.2017.0105
https://www.pnas.org/content/110/45/18190 (Fig 5)

I hope this helps

Vitalii

**Comment by dpcook** [comment]
Hi Vitalii -- thanks for the reply!

The idea would actually be similar to some of the calculations in the royal society paper you linked. Specifically something like Figs 3/4, where they're looking at the angle polymorphism effects to the front. 

Similarly, this recent Nat Comms paper (https://www.nature.com/articles/s41467-019-13195-1) looked at driver mutations and their angle to the front (Fig 3). I've reached out to Jean (first author) about how he calculated it and he recommended the following as an implementation:

> To compute the angle, we use the inner product of the mutation effect
> vector and its projection of the linear subspace spanned by the
> archetypes. Here's the recipe:
> 1. Find an orthonormal basis for the the linear subspace if the
> archetypes. We defined that subspace as the subspace spanned by the
> vector A2-A1, A3-A1, ..., An-A1 where An is the gene expression vector
> of archetype n. Then apply Gram-Schmidt to get an orthonormal basis for
> the archetype subspace.
> 2. Use the orthonormal basis for the archetype subspace to compute the
> projection of the mutation effect vector.
> 3. Take the inner product between the mutation effect vector and its
> projection on the subspace of the archetypes. Make sure to normalize
> both vectors before you do that.
> 4. Finally, apply arccos to the inner product to get the angle.   

I haven't tackled trying to implement it yet, but it seems reasonable. I'll look into this a bit more.

David

**Comment by vitkl** [comment]
Hi David,

I see. This makes sense! I do not have the best documentation to help extent the package but, for this purpose, you can work with archetype coordinates `$XC` in `pch_fit ` object. I don't think I understand how to do points 1 and 2. Would be great if you contribute that to the package. Please let me know if you need help with that.

Vitalii
