### ISSUE TITLE
Error message with fit-pch functions

### ISSUE THREAD

**Issue by annat22** [vitkl/ParetoTI#4]
Hello,
I tried re-running an archetype analysis on a dataset for which I got good results in the past, and this time couldn't get the fitting functions to work. I replicated the error using the simulated example given in the vignette, given below. Looks like the single fit_pch run works, but once bootstrapping is included, it fails.
I would appreciate any help figuring out what it might be.
Thanks for all the hard work you've done on this package, it's been very helpful.

```{r}
 data = generate_data(archetypes$XC, N_examples = 1e4, jiiter = 0.04, size = 0.9)
 
 arc_data = fit_pch(data, noc = as.integer(3), delta = 0)
 
 arc_ks = k_fit_pch(data, ks = 2:6, check_installed = T,
                    bootstrap = T, bootstrap_N = 200, maxiter = 1000,
                    bootstrap_type = "m", seed = 2543, 
                    volume_ratio = "none", # set to "none" if too slow
                    delta=0, conv_crit = 1e-04, order_type = "align",
                    sample_prop = 0.75)
```
Error in pch_fit_list[[1]] : subscript out of bounds
 ```{r}
 arcfit <- fit_pch_bootstrap(data, n = 200, sample_prop = 0.75, seed = 235,
                            noc = 3, delta = 0, conv_crit = 1e-04, type = "m")
```
Error in pch_fit_list[[1]] : subscript out of bounds
 
```

**Comment by vitkl** [comment]
I could reproduce the error with my setup (see `Date and packages used` in the file attached). My guess is that some of the dependency packages changed, and this is causing an error. I will investigate the issue. For now, I would like to suggest you install the same version of the packages as I just used to produce the report attached.

Another guess is that the issue likely resides in how parallel processing is implemented. Can you try  `type = "s"` or `type = "cmq"` and let me know the result?

[Hepatocyte_example.html.zip](https://github.com/vitkl/ParetoTI/files/4183540/Hepatocyte_example.html.zip)

**Comment by vitkl** [comment]
Did different type solve the problem for you?

**Comment by annat22** [comment]
Thanks for the suggestions. The following worked but the figure in plot_arc came out wrong - there's no bootstrap samples and there are three polygons plotted instead of one.

```
arc_ks = k_fit_pch(pcs4arch, ks = 2:6, check_installed = T,
                   bootstrap = T, bootstrap_N = 200, maxiter = 1000,
                   bootstrap_type = "s", seed = 2543, 
                   volume_ratio = "none",
                   delta=0, conv_crit = 1e-04, order_type = "align",
                   sample_prop = 0.75)

arcfit <- fit_pch_bootstrap(pcs4arch, n = 200, sample_prop = 0.75, seed = 235,
                          noc = k, delta = 0, conv_crit = 1e-04, type = "s")

plot_arc(arc_data = arcfit, data = pcs4arch, 
                 which_dimensions = 1:2, line_size = 1.5,
                 data_lab = subtypes[AD,"Subtype"],
                 text_size = 24, data_size = 3, type = "s" 
                  #colors= palette(rainbow(6))
                 ) 
```

**Comment by vitkl** [comment]
I see. Is there any chance for me to test on your data? Could you share
your `pcs4arch` and `subtypes[AD, "subtype"]`?
Also, can you reproduce the tutorial notebook?

**Comment by annat22** [comment]
I'm attaching the objects here - I'd rather not share it on github. The
subtypes object is already filtered for AD, so no need to subset it
further. HTH.
By tutorial notebook do you mean the hepatocyte example you sent me before?
I tried the simulated example but was having problems again with the python
components, even though that was already working fine with my own script
within the same Rproj. I will need to figure it out again and get back to
you on that.
Thanks, Annat

**Comment by annat22** [comment]
You can find the objects here
https://www.dropbox.com/s/az6kimox48e25y4/pcs4arch.RDS?dl=0
and here
https://www.dropbox.com/s/lyxf2mp5dau4vsn/subtypes.RDS?dl=0
The subtypes object is already filtered for AD, so no need to subset it
further.
You can find the simulated example here
https://www.dropbox.com/s/8aseryqakxz8f06/simulatedEx.html?dl=0
Thanks

**Comment by vitkl** [comment]
Thanks for sharing this. I will look into this issue. Yes, I mean that
hepatocyte notebook which is also available on the package website. Would
be good to see if you can reproduce that and if there are any issues.
`py_pcha` is required for core part of polytope fitting in `ParetoTI` so
any issue with that can break analysis. A potential issue with that could
be if you installed `py_pcha` before it was updated to python 3 (prior to
13/06/2019), in which case try installing it into a new python environment
again:
https://github.com/vitkl/ParetoTI#installation
```

conda create -n reticulate_PCHA3 python=3.7.3 pip    # Light install:
source activate reticulate_PCHA3 && pip install --upgrade py_pcha
numpy scipy datetime geosketch umap-learn

# To make sure R uses the correct conda enviroment you can run this
when you start R:
reticulate::use_condaenv
<https://rdrr.io/pkg/reticulate/man/use_python.html>("reticulate_PCHA3",
conda = "auto",
                         required = TRUE)

```

**Comment by vitkl** [comment]
Thanks for sharing this. I will look into this issue. Yes, I mean that
hepatocyte notebook which is also available on the package website. Would
be good to see if you can reproduce that and if there are any issues.
`py_pcha` is required for core part of polytope fitting in `ParetoTI` so
any issue with that can break analysis. A potential issue with that could
be if you installed `py_pcha` before it was updated to python 3 (prior to
13/06/2019), in which case try installing it into a new python environment
again:
https://github.com/vitkl/ParetoTI#installation

```
conda create -n reticulate_PCHA3 python=3.7.3 pip    
# Light install:
source activate reticulate_PCHA3 && pip install --upgrade py_pcha
numpy scipy datetime geosketch umap-learn

# To make sure R uses the correct conda enviroment you can run this
when you start R:
reticulate::use_condaenv("reticulate_PCHA3", conda = "auto", required = TRUE)
```

**Comment by annat22** [comment]
Could you provide a simplified version of the hepatocyte notebook starting with the pcs4arch and final hepatocytes objects? I'm getting error messages in the first chunk and as I don't usually work with this kind of data/packages (I'm applying paretoTI in a different context) it's hard for me to debug. Thanks!

**Comment by annat22** [comment]
As for the python version:
```
> reticulate::py_discover_config("py_pcha")
python:         /Users/habera/Library/r-miniconda/envs/reticulate_PCHA/bin/python
libpython:      /Users/habera/Library/r-miniconda/envs/reticulate_PCHA/lib/libpython3.7m.dylib
pythonhome:     /Users/habera/Library/r-miniconda/envs/reticulate_PCHA:/Users/habera/Library/r-miniconda/envs/reticulate_PCHA
version:        3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/habera/Library/r-miniconda/envs/reticulate_PCHA/lib/python3.7/site-packages/numpy
numpy_version:  1.18.1
py_pcha:        /Users/habera/Library/r-miniconda/envs/reticulate_PCHA/lib/python3.7/site-packages/py_pcha
NOTE: Python version was forced by use_python function
```

**Comment by annat22** [comment]
Hello
I'm still getting error message: Error in pch_fit_list[[1]] : subscript out of bounds
Regardless of what type I use.
I re-installed py_pch into a new environment as you suggested.
Any tips would be appreciated.
Thanks

**Comment by vitkl** [comment]
I believe this was addressed in another issue or via email. If you found a solution please feel free to contribute to this package.

**Comment by JG1ANDONLY** [comment]
Sorry, I run into the same issue. Did you come up with a solution?

**Comment by vitkl** [comment]
Unfortunately no - if you know how to address this please feel free to contribute. 

For some reason, `pch_fit_list` is not a list in this line https://github.com/vitkl/ParetoTI/blob/master/R/fit_pch.R#L964
I don't understand the conditions where it fails.
