### ISSUE TITLE
error reproducing comparison_to_kmeans.Rmd

### ISSUE THREAD

**Issue by annat22** [vitkl/ParetoTI#7]
Hi.
I tried reproducing the example in comparison_to_kmeans.Rmd and for the most part it works well if I use bootstrap_type = "s" instead of "m" in k_fit_pch function (chunk #5). Otherwise I get the same error as with the other datasets: Error in pch_fit_list[[1]] : subscript out of bounds 
The only thing that still doesn't work is (also in chunk #5)
```
lou_cluster_ks = k_fit_pch(data, ks = 2:5,
                           bootstrap = T, bootstrap_N = 200, maxiter = 500,
                           bootstrap_type = "s", clust_options = list(cores = 3),
                           seed = 2543, replace = FALSE,
                           volume_ratio = "none", # set to "none" if too slow
                           sample_prop = 0.95, method = "louvain",
                           method_options = list(resolution = 0.1,
                                                 noc_optim_iter = 500)) # try resolutions for more iterations
```
Error in align_arc(ref_XC, res$pch_fits$XC[[i]]) : 
  align_arc() trying to match different number of archetypes

**Comment by vitkl** [comment]
I believe this was addressed in another issue or via email. If you found a solution please feel free to contribute to this package.
